name: CI

on:
  schedule:
    - cron: "0 9 * * *"
  push:
  pull_request:

jobs:
  build-examples:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i --frozen-lockfile
      - run: bun run build

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install and test
        if: ${{ !(!startsWith(github.event_name, 'pull_request') && contains(runner.os, 'windows')) }}
        run: |
          bun i --frozen-lockfile
          bun run test

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i --frozen-lockfile
      - run: bun run lint

  publish-dry-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i --frozen-lockfile
      - run: bun run publish --dry-run
        working-directory: packages/unplugin-typia

  action-timeline:
    needs:
      - lint
      - test
      - build-examples
      - publish-dry-run
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
