name: CI

env:
  NODE_VERSION: lts/*
  BUN_VERSION: latest
  PACKAGE_DIR: ./packages/unplugin-typia

on:
  schedule:
    - cron: "0 9 * * *"
  push:
  pull_request:

jobs:
  build-examples:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: bun i --frozen-lockfile
      - run: bun run build

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: bun i --frozen-lockfile
      - run: bun run test

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: bun i --frozen-lockfile
      - run: bun run lint

  npm-publish-dry-run-and-upload-pkg-pr-now:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
      - run: bun install --frozen-lockfile
      - run: bun run build
        working-directory: ${{env.PACKAGE_DIR}}
      - run: |
          npm pkg delete private
          bun x pkg-pr-new publish
        working-directory: ${{env.PACKAGE_DIR}}

  action-timeline:
    needs:
      - lint
      - test
      - build-examples
      - npm-publish-dry-run-and-upload-pkg-pr-now
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@427ee2cf860166e404d0d69b4f2b24012bb7af4f # v2.2.3
