name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  jsr:
    env:
      PACKAGE_DIR: ${{github.workspace}}/packages/unplugin-typia
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun i --frozen-lockfile
      - name: copy files
        run: |
          cp LICENSE $PACKAGE_DIR
      - run: bun run publish --allow-dirty
        working-directory: ${{env.PACKAGE_DIR}}

  release:
    needs:
      - jsr
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bunx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
